config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "games#index"

  get 'stats', to: 'pages#stats', as: 'stats'

  get 'history', to: 'pages#history', as: 'history'

  get 'status', to: 'pages#status', as: 'status'

  resources :games do
    resources :game_users, only: %i[create destroy]
    resources :rounds, only: %i[create]
  end
end

app/models/game.rb
require_relative 'player'
require_relative 'go_fish'

class Game < ApplicationRecord
  class InvalidTurn < StandardError; end

  validates :name, presence: true
  validates :required_number_players, presence: true, numericality: { only_integer: true, greater_than: 1 }

  scope :ordered, -> { order(id: :desc) }
  scope :joinable, -> { order(created_at: :desc).where(finished_at: nil).where.not(started_at: nil) }
  scope :in_progress, -> { order(created_at: :desc).where.not(started_at: nil).where(finished_at: nil) }
  scope :no_games, -> { where(created_at: nil) }
  scope :finished, -> { where.not(finished_at: nil) }
  after_update_commit lambda {
                        users.each do |user|
                          broadcast_refresh_to "games:#{id}:users:#{user.id}"
                        end
                        # TODO: Figure out how to broadcast only to the user that is on that page
                        broadcast_refresh_to 'status' if !started_at.nil? && finished_at.nil?
                        broadcast_refresh_to 'history' unless finished_at.nil?
                      }

  has_many :game_users, dependent: :destroy
  has_many :users, through: :game_users

  serialize :go_fish, GoFish

  def self.ransackable_associations(auth_object = nil)
    %w[game_users users]
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at finished_at go_fish id id_value name required_number_players started_at
updated_at]
  end

  def start!
    return false unless enough_players?

    players = users.map { |user| Player.new(user_id: user.id) }
    go_fish = GoFish.new(players:)
    go_fish.deal!
    update(go_fish:, started_at: Time.zone.now)
  end

  def play_round!(user_id, opponent_id, card_rank)
    go_fish.play_round!(user_id, opponent_id, card_rank)

    if go_fish.game_winner
      if go_fish.game_winner.is_a?(Array)
        go_fish.game_winner.each do |winner|
          determine_winner!(winner.user_id)
        end
      else
        determine_winner!(go_fish.game_winner.user_id)
      end
      update(finished_at: Time.zone.now)
    end

    save!
  end

  def enough_players?
    users.count == required_number_players
  end

  def determine_winner!(user_id)
    game_users.find_by(user_id:).update(winner: true)
  end

  def duration
    total_milliseconds = duration_in_milliseconds

    hours = (total_milliseconds / 3_600_000).to_i
    minutes = (total_milliseconds % 3_600_000 / 60_000).to_i
    seconds = (total_milliseconds % 60_000 / 1000).to_i
    milliseconds = (total_milliseconds % 1000).to_i

    format('%02dh:%02dm:%02ds:%03dms', hours, minutes, seconds, milliseconds)
  end

  def duration_in_milliseconds
    return 0 if updated_at.nil? || started_at.nil?

    end_time = finished_at || updated_at
    ((end_time - started_at) * 1000).to_i
  end

  def number_of_rounds_played
    go_fish.round_results.size
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.includes(:users).ordered.page(params[:page]).per(10)
    @user_games = current_user.games.includes(:users)
  end

  def show
    @game = Game.find(params[:id])
    @users = @game.users
  end

  def new
    @game = Game.build
    @path = games_path
    render layout: 'modal'
  end

  def edit
    @game = Game.find(params[:id])
    @path = game_path(@game)
    render layout: 'modal'
  end

  def create
    @game = Game.build(game_params)

    if @game.save
      @game.users << current_user
      respond_to do |format|
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.turbo_stream { flash.now[:notice] = 'Game was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity, layout: 'modal'
    end
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      respond_to do |format|
        format.html { redirect_to games_path, notice: 'Game was successfully updated.' }
        format.turbo_stream { flash.now[:notice] = 'Game was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity, layout: 'modal'
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_path, notice: 'Game was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Game was successfully destroyed.' }
    end
  end

  private

  def game_params
    params.require(:game).permit(:name, :required_number_players, :_method, :authenticity_token, :commit)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.slim
= simple_form_for @game do |f|
  = f.input :name
  = f.input :required_number_players unless editing

  = content_for :modal_actions
    = f.submit class: "btn-primary", form: f.id

app/views/games/_game.html.slim
= turbo_frame_tag game do
  .game-row
    - if game.users.include?(current_user)
      span translate="no" = game.name
      
      .game-actions
        - if game.enough_players?
          span The Game is Full
          span< #{game.users.count}/#{game.required_number_players} Players</span>
        - else
          span< #{game.users.count}/#{game.required_number_players} Players</span>
        = button_to "Delete",
                    game_path(game),
                    method: :delete,
                    class: "btn btn-light"
        = modal_link_to "Edit",
                  edit_game_path(game),
                  class: "btn btn-light"
        = link_to game_path(game), class: "btn btn--medium", data: { turbo_frame: "_top" } do
          |  Play Now
          = material_icon('arrow_right')
                
                
    - else
      span translate="no" = game.name

      .game-actions
        - if game.enough_players?
            span The Game is Full
            span< #{game.users.count}/#{game.required_number_players} Players</span>
        - else
          span> #{game.users.count}/#{game.required_number_players} Players
          = button_to "Join",
                      game_game_users_path(game),
                      method: :post,
                      class: "btn btn--medium",
                      data: { turbo_frame: "_top" }

app/views/games/_game_not_started.html.slim
.game-view
  .go-fish-panel.go-fish-panel--game-board
    .go-fish-panel__header.go-fish-panel__header--game-board
      = link_to games_path('/index'), class: "btn btn--pill btn--icon btn--no-border btn--small back-arrow" do
        | &nbsp;
        | &#8592;
      span translate="no" = @game.name
    .go-fish-panel__body.go-fish-panel__body--game-board
      .players-decks__header
        span Players
      .divider.divider--medium
      .players-hands
                  
  .go-fish-panel.go-fish-panel--game-feed
    .go-fish-panel__header.go-fish-panel__header--game-feed
      span Game Feed
    .go-fish-panel__body.go-fish-panel__body--game-feed
      .notifications data-controller="notifications"
      = form_for @game, url: game_rounds_path(@game), method: :create do |f|
        .actions
          .actions__input-collection
            .form-group
              = label_tag :opponent_id, "Player", class: "form-label"
            .form-group
              span.form-label Card Rank
              .rank-selector(data-controller="rank")
                = hidden_field_tag :rank, '', data: { "rank-target": 'input' }

  .go-fish-panel.go-fish-panel--player-hand.go-fish-panel--bottom-row
    .go-fish-panel__header.go-fish-panel__header-title
      span Your Hand
    .card-tray

  .go-fish-panel.go-fish-panel--player-books.go-fish-panel--bottom-row
    .go-fish-panel__header.go-fish-panel__header-title
      span Your Books
    .card-tray

app/views/games/_game_view.html.slim
.game-view
  .go-fish-panel.go-fish-panel--game-board
    .go-fish-panel__header.go-fish-panel__header--game-board
      = link_to games_path('/index'), class: "btn btn--pill btn--icon btn--no-border btn--small back-arrow" do
        | &nbsp;
        | &#8592;
      span translate="no" = game.name
    .go-fish-panel__body.go-fish-panel__body--game-board
      .players-decks__header
        span Players
      .divider.divider--medium
      .players-hands
        - @game.go_fish.players.each do |player|
          details.accordion
            summary
              = material_icon('arrow_right')
              span.go-fish- translate="no" = player.name
              .flex.gap-lg
                span
                  | Cards:
                  span.go-fish-emphasis= player.hand.size
                span
                  | Books:
                  span.go-fish-emphasis= player.books.size

            .card-tray
              .card-stack.card-stack--accordion-hand
                - if player.user_id == current_user.id
                  - player.hand.each do |card|
                    = image_tag "cards/#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "Playing Card"
                - else
                  - player.hand.each do |card|
                    = image_tag "cards/back-card.svg", alt: "Playing Card"

              .card-stack.card-stack--accordion-books
                - player.books.each do |book|
                  - book.cards.each do |card|
                    = image_tag "cards/#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "Playing Card"

                  
  .go-fish-panel.go-fish-panel--game-feed
    .go-fish-panel__header.go-fish-panel__header--game-feed
      span Game Feed
      button.btn.btn-primary.btn--small
        span translate="no" = "#{@game.go_fish.current_player.name}'s Turn"
    .go-fish-panel__body.go-fish-panel__body--game-feed
      .notifications data-controller="notifications"
        - @game.go_fish.round_results&.each_with_index do |result, index|
          - display_messages = result.messages_for(current_user.name)
          - display_messages.each_with_index do |display_message, message_index|
            .notifications__round_result id="#{result.id}" data-notifications-target="item"
              - if message_index == 0
                .message class=display_message.message_type = display_message.text
              - else
                .indented-message
                  span &#8627;
                  .message class=display_message.message_type = display_message.text
      = form_for @game, url: game_rounds_path(@game), method: :create do |f|
        .actions
          .actions__input-collection
            .form-group
              = label_tag :opponent_id, "Player", class: "form-label"
              = select_tag :opponent_id, options_for_select(@game.go_fish.players.reject { |player| player.user_id == current_user.id }.map { |player| [player.name, player.user_id] }), class: "form-control form-control--small"
            .form-group
              span.form-label Card Rank
              .rank-selector(data-controller="rank")
                = hidden_field_tag :rank, '', data: { "rank-target": 'input' }
                - @game.go_fish.players.find { |player| player.user_id == current_user.id }.hand.map { |card| card.rank }.uniq.each do |rank|
                  = button_tag rank, class: "btn btn--small", data: { action: 'click->rank#select', "rank-target": 'button', rank: rank }

          = f.submit "Ask", class: "btn-primary", disabled: !@game.go_fish.can_take_turn?(current_user.id)

  .go-fish-panel.go-fish-panel--player-hand.go-fish-panel--bottom-row
    .go-fish-panel__header.go-fish-panel__header-title
      span Your Hand
    .card-tray
      - @game.go_fish.players.each do |player|
        - if player.user_id == current_user.id
          .card-stack.card-stack--player-hand
            - player.hand.each do |card|
              = image_tag "cards/#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "Playing Card"

  .go-fish-panel.go-fish-panel--player-books.go-fish-panel--bottom-row
    .go-fish-panel__header.go-fish-panel__header-title
      span Your Books
    .card-tray
      - @game.go_fish.players.each do |player|
        - if player.user_id == current_user.id
          .card-stack.card-stack--player-books
            - player.books.each do |book|
              - book.cards.each do |card|
                = image_tag "cards/#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "Playing Card"    
- if @game.go_fish.game_winner
  = turbo_frame_tag 'modal' do
    .modal-wrapper(
      data-controller="toggle"
      data-toggle-perform-on-connect-value=true
      data-toggle-active-class="modal-wrapper--active"
      data-turbo-cache="false"
      data-action="keydown.esc@window->toggle#off"
    )
      .modal-wrapper__backdrop data-action="click->toggle#off"
      .modal data-testid="modal-content"
        .modal__header
          span There is a winner!
          = button_tag( material_icon('close', size: 'x-large'), class: 'btn btn--no-border btn--icon btn--pill', data: { action: "toggle#off" })

        .modal__body
          - winner_names = @game.go_fish.determine_winner_names
          - if winner_names
            span = "#{winner_names} wins!"
          - else
            span = "No winners!"

        .modal__footer
          = link_to 'Home', games_path, class: "btn-primary", target: "_top"

app/views/games/create.turbo_stream.slim
= turbo_stream.append "your_games", @game
= turbo_stream.append "all_games", @game
= turbo_stream.update Game.new, ""
= render_turbo_stream_flash_messages
= turbo_stream.replace 'modal' do
  = turbo_frame_tag 'modal' do
    script
      | document.dispatchEvent(new CustomEvent('modal:close'));

app/views/games/destroy.turbo_stream.slim
= turbo_stream.remove_all @game
= render_turbo_stream_flash_messages

app/views/games/edit.html.slim
= content_for :modal_title
  h1 Edit Game

= render "form", editing: true

app/views/games/index.html.slim
.games-list
  .your-games
    .games-list-header
      span Your Games
      = modal_link_to new_game_path, class: "btn btn-primary btn--medium" do
        = image_tag "add_button.svg"
        |  New game
    = turbo_frame_tag "your_games", class: "turbo-row" do
      - if @user_games.any?
        - @user_games.each do |game|
          = render 'game', game: game
      - else
        p You are not in any games
  .all-games
    .games-list-header
      span All Games
    = turbo_frame_tag "all_games" do
      .turbo-row
        - if @games.any?
          - @games.each do |game|
            = render 'game', game: game
        - else
          p There are no games available
  .pagination
    = paginate @games

app/views/games/new.html.slim
= content_for :modal_title
  h1 New game

= render "form", game: @game, editing: false

app/views/games/show.html.slim
= turbo_stream_from "games:#{@game.id}:users:#{current_user.id}"

- if @game.go_fish
  = render 'games/game_view', game: @game
- else
  = render 'games/game_not_started'

app/views/games/update.turbo_stream.slim
= turbo_stream.update_all @game
= render_turbo_stream_flash_messages
= turbo_stream.replace 'modal' do
  = turbo_frame_tag 'modal' do
    script
      | document.dispatchEvent(new CustomEvent('modal:close'));