config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: "games#index"

  get 'stats', to: 'pages#stats', as: 'stats'

  get 'history', to: 'pages#history', as: 'history'

  get 'status', to: 'pages#status', as: 'status'

  resources :games do
    resources :game_users, only: %i[create destroy]
    resources :rounds, only: %i[create]
  end
end

app/views/layouts/_flash.html.slim
- flash.each do |flash_type, message|
  .alert--flash class="alert-#{flash_type}" data-controller="removals" data-action="animationend->removals#remove"
    = message

app/views/layouts/_navbar.html.slim
header.navbar
  - if user_signed_in?
    .navbar__name
      = link_to games_path('/index'), class: "go-fish-logo", translate: "no" do
        | Go Fish
      .divider-vertical
      span translate="no" = current_user.name
    = button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn--dark"
  - else
    = link_to "Sign in", new_user_session_path, class: "btn btn--dark navbar__right"

app/views/layouts/_sidebar.html.slim
.sidebar.sidebar--drawer
  .sidebar__content.sidebar__content--start
    .sidebar-header
      = link_to games_path do
        = image_tag "Go-Fish-Logo.png", alt: "Go Fish Logo"
    .divider.divider--medium
    = link_to games_path, class: "btn btn--no-border" do
      = material_icon('joystick')
      | Games
    = link_to stats_path, class: "btn btn--no-border" do
      = material_icon('query_stats')
      | Stats
    = link_to history_path, class: "btn btn--no-border" do
      = material_icon('history')
      | History
    = link_to status_path, class: "btn btn--no-border" do
      = material_icon('set_meal')
      | Status

  .sidebar__content.sidebar__content--end
    .divider.divider--medium
    button.btn.btn--no-border
      = material_icon('person_book')
      | Profile
    = button_to destroy_user_session_path, method: :delete, style: "color: var(--op-color-primary-on-plus-max);", class: "btn btn--no-border full-width text-justify-left", data: { turbo: false } do
      = material_icon('logout')
      | Log Out

app/views/layouts/application.html.slim
doctype html
html
  head
    title(translate="no") Go Fish Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
    meta name="turbo-refresh-method" content="morph"
    meta name="view-transition" content="same-origin"
    meta name="turbo-refresh-scroll" content="preserve"
    meta content="width=device-width, initial-scale=1" name="viewport"
    - game_show_page = controller_name == 'games' && action_name == 'show'
    - app_class = game_show_page ? 'app-body' : 'app-with-sidebar'
  body class=app_class
    - if game_show_page
      .app__header
        = render "layouts/navbar"
    - else
      = render "layouts/sidebar"
    .app-body
      #flash
        = render "layouts/flash"
      = turbo_frame_tag 'modal'
      = turbo_frame_tag 'panel'
      = render 'confirm'
      - if game_show_page
        = yield
      - else
        .app__content
          = yield

app/views/layouts/modal.html.slim
doctype html
html
  head
    title Go Fish Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body
    = turbo_frame_tag 'modal' do
      .modal-wrapper(
        class=class_names('modal-wrapper--active' => response.status == 422)
        data-controller="toggle"
        data-toggle-perform-on-connect-value=(response.message == 'OK')
        data-toggle-active-class="modal-wrapper--active"
        data-turbo-cache="false"
        data-action="keydown.esc@window->toggle#off"
      )
        .modal-wrapper__backdrop data-action="click->toggle#off"
        .modal data-testid="modal-content"
          .modal__header(translate="no")
            = yield :modal_title
            = button_tag( material_icon('close', size: 'x-large'), class: 'btn btn--no-border btn--icon btn--pill', data: { action: "toggle#off" })

          .modal__body
            = yield

          .modal__footer
            = button_tag( 'Cancel', class: 'btn', data: { action: "toggle#off" })
            = yield :modal_actions

app/views/layouts/panel.html.slim
doctype html
html
  head
    title Go Fish Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body
    = turbo_frame_tag 'panel' do
      .panel.flex.items-center.justify-center(
        data-testid='panel'
        class=class_names('panel--active' => response.message == 'Unprocessable Entity')
        data-controller="toggle"
        data-toggle-perform-on-connect-value=(response.message == 'OK')
        data-toggle-active-class="panel--active"
        data-turbo-cache="false"
      )
        .panel__content
          .modal-nav
            .panel__close data-action="click->toggle#perform"
              = icon('close')
          .panel__body
            = yield